import streamlit as st
import matplotlib.pyplot as plt

from automation import process_data
from report_generator import generate_report


# --------------------------------
# PAGE CONFIGURATION
# --------------------------------

st.set_page_config(
    page_title="AutoReport",
    page_icon="📊",
    layout="wide"
)


# --------------------------------
# HEADER
# --------------------------------

st.title("📊 AutoReport")

st.markdown(
    "### Automated Business Report & Follow-up System"
)

st.write(
    "Turn raw business data into clean insights, reports, "
    "and actionable follow-up tasks — automatically."
)

st.divider()


# --------------------------------
# FILE UPLOAD
# --------------------------------

st.subheader("📁 Upload Business Data")

uploaded_file = st.file_uploader(
    "Upload a CSV or Excel file",
    type=["csv", "xlsx"]
)


# --------------------------------
# RUN AUTOMATION
# --------------------------------

if uploaded_file is not None:

    st.success("✅ File uploaded successfully!")

    if st.button("🚀 Run Automation", use_container_width=True):

        with st.spinner("⚙️ Running AutoReport automation..."):

            df, summary, issues, insights = process_data(
                uploaded_file
            )

            report_path = generate_report(
                df,
                summary,
                issues
            )

        st.success("🎉 Automation completed successfully!")


        # --------------------------------
        # REPORT DOWNLOAD
        # --------------------------------

        st.subheader("📄 Generated Report")

        with open(report_path, "rb") as file:

            st.download_button(
                label="📥 Download Excel Report",
                data=file,
                file_name="AutoReport_Report.xlsx",
                mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                use_container_width=True
            )


        # --------------------------------
        # BUSINESS SUMMARY
        # --------------------------------

        st.divider()

        st.subheader("📊 Business Summary")

        col1, col2, col3, col4 = st.columns(4)

        col1.metric(
            "💰 Total Sales",
            f"₹{summary['total_sales']:,.0f}"
        )

        col2.metric(
            "🛒 Total Orders",
            summary["total_orders"]
        )

        col3.metric(
            "📦 Average Order Value",
            f"₹{summary['average_order_value']:,.0f}"
        )

        col4.metric(
            "🏆 Top Product",
            summary["top_product"]
        )


        # --------------------------------
        # DATA QUALITY
        # --------------------------------

        st.divider()

        st.subheader("🔍 Data Quality")

        col1, col2, col3 = st.columns(3)

        col1.metric(
            "📋 Original Records",
            summary["original_rows"]
        )

        col2.metric(
            "♻️ Duplicates Removed",
            summary["duplicates"]
        )

        col3.metric(
            "⚠️ Missing Values",
            summary["missing_values"]
        )


        # --------------------------------
        # ISSUES DETECTED
        # --------------------------------

        st.divider()

        st.subheader("⚠️ Issues Detected")

        if issues:

            for issue in issues:
                st.warning(issue)

        else:

            st.success(
                "✅ No issues detected. Your data looks healthy!"
            )


        # --------------------------------
        # AUTOMATED INSIGHTS
        # --------------------------------

        st.divider()

        st.subheader("🧠 Automated Business Insights")

        for insight in insights:
            st.info("💡 " + insight)


        # --------------------------------
        # BUSINESS ANALYTICS
        # --------------------------------

        st.divider()

        st.subheader("📈 Business Analytics")


        # Sales by Product

        st.markdown("#### 💰 Sales by Product")

        sales_by_product = (
            df.groupby("Product")["Sales"]
            .sum()
            .sort_values(ascending=False)
        )

        fig1, ax1 = plt.subplots(figsize=(10, 4))

        sales_by_product.plot(
            kind="bar",
            ax=ax1
        )

        ax1.set_xlabel("Product")
        ax1.set_ylabel("Sales (₹)")
        ax1.set_title("Revenue Generated by Product")

        plt.xticks(rotation=45)

        st.pyplot(fig1)

        plt.close(fig1)


        # Order Status

        st.markdown("#### 📦 Order Status")

        status_counts = df["Status"].value_counts()

        fig2, ax2 = plt.subplots(figsize=(8, 4))

        status_counts.plot(
            kind="bar",
            ax=ax2
        )

        ax2.set_xlabel("Order Status")
        ax2.set_ylabel("Number of Orders")
        ax2.set_title("Order Status Distribution")

        plt.xticks(rotation=0)

        st.pyplot(fig2)

        plt.close(fig2)


        # --------------------------------
        # FOLLOW-UP TASKS
        # --------------------------------

        st.divider()

        st.subheader("✅ Automated Follow-up Tasks")

        task_count = 0


        if summary["cancelled_orders"] > 0:

            st.error(
                "🔴 HIGH PRIORITY — Review cancelled orders"
            )

            task_count += 1


        if summary["pending_orders"] > 0:

            st.warning(
                "🟠 MEDIUM PRIORITY — Follow up on pending orders"
            )

            task_count += 1


        if summary["duplicates"] > 0:

            st.warning(
                "🟡 MEDIUM PRIORITY — Review duplicate records"
            )

            task_count += 1


        if summary["missing_values"] > 0:

            st.info(
                "🔵 LOW PRIORITY — Review missing data"
            )

            task_count += 1


        if task_count == 0:

            st.success(
                "🎉 No follow-up tasks required!"
            )


        # --------------------------------
        # CLEANED DATA
        # --------------------------------

        st.divider()

        st.subheader("📋 Cleaned & Processed Data")

        st.dataframe(
            df,
            use_container_width=True,
            height=400
        )


        # --------------------------------
        # COMPLETION
        # --------------------------------

        st.divider()

        st.success(
            "✅ AutoReport has completed the full automation workflow."
        )